<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Корзина");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"basket-new", 
	array(
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"COLUMNS_LIST" => array(
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "WEIGHT",
			3 => "PROPS",
			4 => "DELETE",
			5 => "DELAY",
			6 => "TYPE",
			7 => "PRICE",
			8 => "QUANTITY",
			9 => "SUM",
			10 => "PROPERTY_VES_M2",
			11 => "PROPERTY_SHIRINA_LISTA",
			12 => "PROPERTY_DUPUSTIMYE_RAZMERY_METALLOCHEREPITSA_MM",
			13 => "PROPERTY_DLINA",
			14 => "PROPERTY_KRASKA",
			15 => "PROPERTY_CML2_BAR_CODE",
			16 => "PROPERTY_CML2_ARTICLE",
			17 => "PROPERTY_CML2_ATTRIBUTES",
			18 => "PROPERTY_CML2_TRAITS",
			19 => "PROPERTY_CML2_BASE_UNIT",
			20 => "PROPERTY_CML2_TAXES",
			21 => "PROPERTY_MORE_PHOTO",
			22 => "PROPERTY_FILES",
			23 => "PROPERTY_CML2_MANUFACTURER",
			24 => "PROPERTY_SALE",
			25 => "PROPERTY_POKRYTIE",
			26 => "PROPERTY_TYPE_LENGTH",
			27 => "PROPERTY_PROIZVODITEL",
			28 => "PROPERTY_OBEM",
			29 => "PROPERTY_TOLSHCHINA_MM",
			30 => "PROPERTY_VES_KG",
			31 => "PROPERTY_VYSOTA",
			32 => "PROPERTY_KOEFFITSIENT_M2_SHT",
			33 => "PROPERTY_M2",
			34 => "PROPERTY_TIP_PROFILYA",
			35 => "PROPERTY_TSVET_POKRYTIYA",
			36 => "PROPERTY_SHIRINA",
			37 => "PROPERTY__1200KH1800",
			38 => "PROPS",
		),
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"PATH_TO_ORDER" => "/personal/order/make/",
		"HIDE_COUPON" => "N",
		"QUANTITY_FLOAT" => "N",
		"PRICE_VAT_SHOW_VALUE" => "Y",
		"TEMPLATE_THEME" => "blue",
		"SET_TITLE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"OFFERS_PROPS" => array(
		),
		"COMPONENT_TEMPLATE" => "basket-new",
		"USE_PREPAYMENT" => "N",
		"AUTO_CALCULATION" => "Y",
		"ACTION_VARIABLE" => "basketAction",
		"USE_GIFTS" => "Y",
		"GIFTS_PLACE" => "BOTTOM",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_SHOW_OLD_PRICE" => "N",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MESS_BTN_DETAIL" => "Подробнее",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_CONVERT_CURRENCY" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N",
		"CORRECT_RATIO" => "N",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
			6 => "PROPERTY_DLINA",
		),
		"COMPATIBLE_MODE" => "Y",
		"ADDITIONAL_PICT_PROP_24" => "-",
		"ADDITIONAL_PICT_PROP_29" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive"
	),
	false
);?>


<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>